CLASS zma_main_test DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES: if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZMA_MAIN_TEST IMPLEMENTATION.


 METHOD if_oo_adt_classrun~main.

 UPDATE /xfc/srm_rect02a set cl_ui5 = '/XFC/CL_TASK_UI5_CTRL_TRY' where REC_ID = 'ZXFC_T01_TASK_TEMPLATE'.

 ENDMETHOD.
ENDCLASS.
